info_complementaire:
    resource: "@InfoComplementaireBundle/Resources/config/routing.yml"
    prefix:   /

authentification:
    resource: "@AuthentificationBundle/Resources/config/routing.yml"
    prefix:   /

