voyage_homepage:
    path:     /voyages
    defaults: { _controller: ReservationBundle:Voyage:index }
voyage_destinationpage:
    path:     /voyages/{id}
    defaults: { _controller: ReservationBundle:Voyage:voyage }
